### ISSUE TITLE
Investigate part 6 for encryption flag

### ISSUE THREAD

**Issue by victorbush** [victorbush/ego.nefsedit#10]
It looks like part 6 might contain a flag indicating whether an item's data is encrypted. Compare an encrypted nefs with a non-encrypted one. One of the part 6 fields often has a value of either "3" or "1" depending on if encrypted.

Needs investigation, this is a hunch. Could be a bitfield of some kind.

If there is a flag that indicates if the data is encrypted, then nefsedit/nefslib should use this flag when extracting files.

**Comment by Gigi1237** [comment]
In the old 10600 format it is almost certainly a bitfield

**Comment by victorbush** [comment]
Added in 0.6.0.

The format for part 6 in nefs version 2.0 appears to be the same as 1.6; however, the flags are different. I've identified a few of them for 2.0 and have documented them in the wiki. The flag fields are now used to determine encryption/compression and also whether an item is a directory or not.
