### ISSUE TITLE
F1 2020

### ISSUE THREAD

**Issue by alemag88** [victorbush/ego.nefsedit#17]
Hello any news on been able to modify and save 1.6 version for Codemasters F1 2020 please?
Thanks

**Comment by victorbush** [comment]
Currently have no plans to support this. As far as I'm aware, f1 uses a game.dat/game.bin format (similar to other games using nefs 1.6). This means the header data is stored in the game executable. Modifying the files would require either modifying the exe, or maybe doing some kind of runtime injection. Neither is trivial.

**Comment by alemag88** [comment]
Well that's a shame,thanks for the reply though

**Comment by victorbush** [comment]
Moved 1.6 support into it's own issue (https://github.com/victorbush/ego.nefsedit/issues/20) and closing this as duplicate.
