### ISSUE TITLE
Add support for saving encrypted Archives Dirt Rally 2.0

### ISSUE THREAD

**Issue by Fabio-Git-dev** [victorbush/ego.nefsedit#18]
![image](https://user-images.githubusercontent.com/30447649/97037116-23b8e000-1569-11eb-94f7-77d8c982323b.png)
The archives can be opened and edited, but can't save the modifications to them

**Comment by Fabio-Git-dev** [comment]
Is this project still active?

**Comment by victorbush** [comment]
See https://github.com/victorbush/ego.nefsedit/issues/20.

**Comment by victorbush** [comment]
This won't be supported. There's no way to save an encrypted archive. The first 80 bytes of the header are encrypted with RSA-1024 (i.e, public/private key pair). We can only decrypt, we'd need Codemasters' key to re-encrypt this data. This section of the header has the expected hash of the archive, if its incorrect the game will crash.
